let suggestedResultsArray=[
        '<img id="defaultSuggestion" src="images/spinach.png" width="55%" height="auto">',
         '<img id="defaultSuggestion" src="images/avocado.png" width="55%" height="auto">',

        '<img id="defaultSuggestion" src="images/bag.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/borocli.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/veggie01.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/veggie02.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/raddish.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/califlower.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/carrot.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/celery.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/corn.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/lettuce.png" width="55%" height="auto">',
             '<img id="defaultSuggestion" src="images/coconut.png" width="55%" height="auto">',

        '<img id="defaultSuggestion" src="images/lettuce02.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/onion.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/potato.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/potato2.png" width="55%" height="auto">',
           '<img id="defaultSuggestion" src="images/papaya.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/sweetMelon.png" width="55%" height="auto">',
            '<img id="defaultSuggestion" src="images/tumeric.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/banana.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/bamboo.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/bean.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/cucumber.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/brocoli02.png" width="55%" height="auto">',
    
        '<img id="defaultSuggestion" src="images/cabbage02.png" width="55%" height="auto">',
            '<img id="defaultSuggestion" src="images/chill.png" width="55%" height="auto">',

        '<img id="defaultSuggestion" src="images/cabbage03.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/kiwi.png" width="55%" height="auto">',
                  '<img id="defaultSuggestion" src="images/mango.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/corn02.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/beets.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/lettuce04.png" width="55%" height="auto">',
    
        '<img id="defaultSuggestion" src="images/lettuce05.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/mint.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/orange.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/pea.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/raddish02.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/sweetpotato.png" width="55%" height="auto">',
         '<img id="defaultSuggestion" src="images/ginger.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/durain02.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/apple03.png" width="55%" height="auto">',
    
        '<img id="defaultSuggestion" src="images/strawberry.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/tomato.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/squash.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/arugula.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/zuchini.png" width="55%" height="auto">',
    
            '<img id="defaultSuggestion" src="images/egg.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/eggplant.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/passionfruit.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/punmkin.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/mushroom05.png" width="55%" height="auto">',
    
        '<img id="defaultSuggestion" src="images/lettuce08.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/sweetpotato02.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/lettuce07.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/pepper.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/blueberries.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/lettuce06.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/mushroom.png" width="55%" height="auto">',
                  '<img id="defaultSuggestion" src="images/watermelons.png" width="55%" height="auto">',

        '<img id="defaultSuggestion" src="images/mushroom02.png" width="55%" height="auto">',
           '<img id="defaultSuggestion" src="images/passionfruit02.png" width="55%" height="auto">',
            '<img id="defaultSuggestion" src="images/sweetApple.png" width="55%" height="auto">',
           
        '<img id="defaultSuggestion" src="images/mushroom03.png" width="55%" height="auto">',
                     '<img id="defaultSuggestion" src="images/mango02.png" width="55%" height="auto">',

        '<img id="defaultSuggestion" src="images/watermelon.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/banana.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/quailegg.png" width="55%" height="auto">',
    
            '<img id="defaultSuggestion" src="images/starfruit.png" width="55%" height="auto">',

        '<img id="defaultSuggestion" src="images/mushroom04.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/mushroom06.png" width="55%" height="auto">',
   
     '<img id="defaultSuggestion" src="images/appleSlice.png" width="55%" height="auto">',
    '<img id="defaultSuggestion" src="images/dragonfruit.png" width="55%" height="auto">',
             '<img id="defaultSuggestion" src="images/durian01.png" width="55%" height="auto">',
                 '<img id="defaultSuggestion" src="images/durian03.png" width="55%" height="auto">',
                 '<img id="defaultSuggestion" src="images/durian04.png" width="55%" height="auto">',
                     '<img id="defaultSuggestion" src="images/durian05.png" width="55%" height="auto">',
                 '<img id="defaultSuggestion" src="images/jackfruitpieces.png" width="55%" height="auto">',        
                 '<img id="defaultSuggestion" src="images/mango03.png" width="55%" height="auto">',
                '<img id="defaultSuggestion" src="images/MangoCutouts.png" width="55%" height="auto">',
                    '<img id="defaultSuggestion" src="images/melon.png" width="55%" height="auto">',
         
             '<img id="defaultSuggestion" src="images/watermelon02.png" width="55%" height="auto">',
             '<img id="defaultSuggestion" src="images/watermelonSlices.png" width="55%" height="auto">',





    
     
];


let banArray=[   
    '<img id="defaultSuggestion" src="images/chai.png" width="55%" height="auto">',
     '<img id="defaultSuggestion" src="images/ban02.png" width="55%" height="auto">',
     '<img id="defaultSuggestion" src="images/twisting.png" width="55%" height="auto">',
     '<img id="defaultSuggestion" src="images/banned.png" width="55%" height="auto">',
     '<img id="defaultSuggestion" src="images/notOkay.png" width="55%" height="auto">',
    '<img id="defaultSuggestion" src="images/notOkay.png" width="55%" height="auto">',
            '<img id="defaultSuggestion" src="images/cuoqi.png" width="55%" height="auto">',
        '<img id="defaultSuggestion" src="images/sensitive.png" width="55%" height="auto">',
            '<img id="defaultSuggestion" src="images/cene01.png" width="55%" height="auto">',
            '<img id="defaultSuggestion" src="images/cene03.png" width="55%" height="auto">',
            '<img id="defaultSuggestion" src="images/cene02.png" width="55%" height="auto">',
            '<img id="defaultSuggestion" src="images/cene05.png" width="55%" height="auto">',
            '<img id="defaultSuggestion" src="images/twisting.png" width="55%" height="auto">',
             '<img id="defaultSuggestion" src="images/loading.png" width="55%" height="auto">',
             '<img id="defaultSuggestion" src="images/whocare.png" width="55%" height="auto">',

];


let veggiesArray=[
    'durian',
    'sugar apple',
    'papaya slices',
    'blurberries',
    'avocado',
    'mint',
    'melon',
    'watermelon',
    'ginger',
    'tumeric',
    'dragonfruit',
    'starfruit',
    'kiwifruit',
    'passionfruit',
    'apple slices',
    'jackfruitpeel',
    'mango',
    'coconut',
    'bamboo',
    'quail egg',
    'mushroom',
    'sweet potato',
    'lettuce',
    'egg',
    'strawberry',
    'cabbage',
    'pea',
    'banana',
    'eggplant',
    'cucumber',
    'potato',
    'purple lettuce',
    'brocoli',
    'califlower',
    'beets',
    'orange',
    'raddish',
    'pepper',
    'tomato',
    'raddish',
    'onion',
    'zuchini',
    'carrot',
    'chili',
    'corn',
    'potato',
    'bean',
    'squash',
    'corn',
    'pumpkin',
    
];

let veggiesArray_cn =[
    '榴莲',
    '糖苹果',
    '木瓜片',
    '蓝莓',
    '牛油果',
    '薄荷',
    '瓜',
    '西瓜',
    '姜',
    '姜黄',
    '火龙果',
    '杨桃',
    '奇异果',
    '百香果',
    '苹果片',
    '菠萝蜜皮',
    '芒果',
    '椰子',
    '竹子',
    '鹌鹑蛋',
    '蘑菇',
    '甘薯',
    '莴苣',
    '蛋',
    '草莓',
    '卷心菜',
    '豌豆',
    '香蕉',
    '茄子',
    '黄瓜',
    '土豆',
    '紫色生菜',
    '西兰花',
    '花椰菜',
    '甜菜',
    '橙子',
    '萝卜',
    '胡椒',
    '番茄',
    '萝卜',
    '洋葱',
    '西葫芦',
    '胡萝卜',
    '辣椒',
    '玉米',
    '土豆',
    '豆',
    '壁球',
    '玉米',
    '南瓜',
]

